[package]
name = "rest_rav_detector"
version = "0.1.0"
edition = "2021"

[dependencies]
onnxruntime = { version = "0.0.14", optional = true }
image = { version = "0.24", optional = true }
serde = { version = "1.0", features = ["derive"] }

[features]
visual-validation = ["onnxruntime", "image"]
