[package]
name = "motor_cortex"
version.workspace = true
edition.workspace = true

[lib]
name = "motor_cortex"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
nalgebra = "0.32"
tch = "0.23"
log = "0.4"

[package.metadata.forge]
LIBTORCH_BYPASS_VERSION_CHECK = "1"
