[package]
name = "restav_detector"
version = "0.1.0"
edition = "2021"

[dependencies]
[dependencies]
onnxruntime = { version = "0.0.14", optional = true }
image = { version = "0.24", optional = true }

[features]
visual-validation = ["dep:onnxruntime", "dep:image"]
