[package]
name = "restav_detector"
version = "0.1.0"
edition = "2021"

[dependencies]
onnxruntime = { version = "0.9", optional = true }
image = { version = "0.24", optional = true }

[features]
default = []
onnxruntime = ["dep:onnxruntime", "dep:image"]
