[package]
name = "hillium_backend"
version.workspace = true
edition.workspace = true

[lib]
name = "hillium_backend"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
numpy = "0.20"
